name: "Deploy to CDN"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Get changed files
        id: changed-files
        run: |
          echo "files=$(git diff --name-only HEAD~1 HEAD | xargs)" >> $GITHUB_OUTPUT

      - name: Build tool
        if: steps.changed-files.outputs.files
        run: |
          cd tools
          go build -o ../tools-cli .
          cd ..

      - name: Package and Generate Index
        if: steps.changed-files.outputs.files
        run: |
          ./tools-cli package
          ./tools-cli generate-index --cdn-url "https://${{ vars.S3_BUCKET_NAME }}.s3.${{ vars.AWS_REGION }}.amazonaws.com"

      - name: Deploy Content to CDN
        if: steps.changed-files.outputs.files
        run: |
          aws s3 sync ./dist/ s3://${{ vars.S3_BUCKET_NAME }}/
          aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"