name: Dependency Pull Request Review

on:
  pull_request:
    branches: [ main ]


jobs:
  validate:
    name: Validate Pull Request
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build CLI Tool
        run: go build -v -o dep-tools .

      - name: Validate PR Structure
        run: ./dep-tools validate-pr --path ${{ github.event.pull_request.head.repo.full_name }} --pr ${{ github.event.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      